#!/bin/bash
GOOS=darwin GOARCH=amd64 go build -o sbtl-darwin-amd64
GOOS=darwin GOARCH=arm64 go build -o sbtl-darwin-arm64
GOOS=linux GOARCH=amd64 go build -o sbtl-linux-amd64
GOOS=linux GOARCH=arm64 go build -o sbtl-linux-arm64
GOOS=windows GOARCH=amd64 go build -o sbtl-windows-amd64
GOOS=windows GOARCH=arm64 go build -o sbtl-windows-arm64